### ISSUE TITLE
GenerateAssemblyList failing with could not find file ...dependencylist.txt

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#821] opened 2016-06-16 20:43 UTC
To repro on an Ubuntu machine fetch master, init-tools, then build one test with /t:BuildAndTest.

Expect: run test

Actual: build fails with
```
/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(213,5): error MSB4018: The "GenerateAssemblyList" task failed unexpectedly. [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj]
/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(213,5): error MSB4018: System.IO.FileNotFoundException: Could not find file '/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/bin/TestDependencies/Microsoft.CSharp.Tests-AnyOS.AnyCPU.Debug.netcoreapp1.0.dependencylist.txt'. [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj]
/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(213,5): error MSB4018: File name: '/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/bin/TestDependencies/Microsoft.CSharp.Tests-AnyOS.AnyCPU.Debug.netcoreapp1.0.dependencylist.txt' [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj]
/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(213,5): error MSB4018:    at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter) [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj]
/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(213,5): error MSB4018:    at Interop.CheckIo[TSafeHandle](TSafeHandle handle, String path, Boolean isDirectory, Func`2 errorRewriter) [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj]
/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(213,5): error MSB4018:    at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode) [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj]
/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(213,5): error MSB4018:    at System.IO.UnixFileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent) [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj]
/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(213,5): error MSB4018:    at System.IO.UnixFileSystem.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, FileStream parent) [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj]
/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(213,5): error MSB4018:    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options) [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj]
/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(213,5): error MSB4018:    at Microsoft.DotNet.Build.Tasks.GenerateAssemblyList.Execute() [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj]
/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(213,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj]
/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/Tools/tests.targets(213,5): error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() [/mnt/j/workspace/dotnet_corefx/master/ubuntu14.04_debug_prtest/src/Microsoft.CSharp/tests/Microsoft.CSharp.Tests.csproj]
```

**Comment by ericstj** [comment] 2016-06-16 20:44
FWIW it looks like this doesn't repro if TestWithLocalLibraries=true, which is why the CI isn't failing.

**Comment by ericstj** [comment] 2016-06-16 21:35
I looked at it a bit more and found the problem is that IncludedFileForRunnerScript is empty.  I suspect this was broken by @karajas here https://github.com/dotnet/buildtools/commit/dbf81d43533f82d795234cc8b4fc9aa4c857d9ac#diff-425cb0dcf83ca9680e4a736c021dabe8R185

**Comment by karajas** [comment] 2016-06-16 21:38
Yes I introduced a workaround to avoid the issues that were resolved by https://github.com/dotnet/buildtools/commit/d2f3d75df4a5dd896eb72138c42c159feb71522a . Should have a fix which solves this and the issue with the tests assemblies getting copied to the test directory.

**Closed** 2016-06-16 22:57 UTC

**Comment by ctyar** [comment] 2016-07-03 16:00
I'm having same issue in win7 with same steps
```
RunTestsForProject:
  Creating directory "C:\corefx\bin//TestDependencies"
  .
  Generating C:\corefx\bin//TestDependencies/System.Co
  llections.Tests-AnyOS.AnyCPU.Debug.netcoreapp1.0.dependencylist.txt
  Generating JSON-Processed C:\corefx\bin/AnyOS.AnyCPU
  .Debug/System.Collections.Tests/assemblylist.txt for legacy execution
C:\corefx\Tools\tests.targets(200,5): error MSB4018: T
he "GenerateAssemblyList" task failed unexpectedly.\r [C:\Shahriar\Projects\asp
net\corefx\src\System.Collections\tests\System.Collections.Tests.csproj]
C:\corefx\Tools\tests.targets(200,5): error MSB4018: S
ystem.IO.FileNotFoundException: Could not find file 'C:\Shahriar\Projects\aspne
t\corefx\bin\TestDependencies\System.Collections.Tests-AnyOS.AnyCPU.Debug.netco
reapp1.0.dependencylist.txt'.\r [C:\corefx\src\System.
Collections\tests\System.Collections.Tests.csproj]
C:\corefx\Tools\tests.targets(200,5): error MSB4018: F
ile name: 'C:\corefx\bin\TestDependencies\System.Colle
ctions.Tests-AnyOS.AnyCPU.Debug.netcoreapp1.0.dependencylist.txt'\r [C:\Shahria
r\Projects\aspnet\corefx\src\System.Collections\tests\System.Collections.Tests.
csproj]
C:\corefx\Tools\tests.targets(200,5): error MSB4018:
  at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)\r [C:\
Shahriar\Projects\aspnet\corefx\src\System.Collections\tests\System.Collections
.Tests.csproj]
C:\corefx\Tools\tests.targets(200,5): error MSB4018:
  at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, I
nt32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions
options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Bool
ean useLongPath, Boolean checkHost)\r [C:\corefx\src\S
ystem.Collections\tests\System.Collections.Tests.csproj]
C:\corefx\Tools\tests.targets(200,5): error MSB4018:
  at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access,
FileShare share)\r [C:\corefx\src\System.Collections\t
ests\System.Collections.Tests.csproj]
C:\corefx\Tools\tests.targets(200,5): error MSB4018:
  at Microsoft.DotNet.Build.Tasks.GenerateAssemblyList.Execute()\r [C:\Shahriar
\Projects\aspnet\corefx\src\System.Collections\tests\System.Collections.Tests.c
sproj]
C:\corefx\Tools\tests.targets(200,5): error MSB4018:
  at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExe
cutionHost.Execute()\r [C:\corefx\src\System.Collectio
ns\tests\System.Collections.Tests.csproj]
C:\corefx\Tools\tests.targets(200,5): error MSB4018:
  at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNex
t() [C:\corefx\src\System.Collections\tests\System.Col
lections.Tests.csproj]
Done Building Project "C:\corefx\src\System.Collection
s\tests\System.Collections.Tests.csproj" (Test target(s)) -- FAILED.


Build FAILED.
```

**Comment by jamesqo** [comment] 2016-07-04 00:18
I'm having this same issue, as well.

**Comment by ctyar** [comment] 2016-07-04 16:49
Cant reproduce on https://github.com/dotnet/corefx/commit/3e82a5722cf8b847cb510e16b06aaa98a25bc07f anymore
