### ISSUE TITLE
Error in init-tools.sh on Debian

### ISSUE THREAD

**Issue by gkhanna79** [dotnet/buildtools#502] opened 2016-03-01 22:19 UTC
I see the following error in init-tools.sh restored from BuildTools package:

2016-03-01T22:10:15.270Z: /root/coreclr/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00177/lib/init-tools.sh: 38: /root/coreclr/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00177/lib/init-tools.sh: source: not found
2016-03-01T22:10:15.270Z: /root/coreclr/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00177/lib/init-tools.sh: 39: [: unexpected operator
2016-03-01T22:10:15.270Z: /root/coreclr/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00177/lib/init-tools.sh: 41: [: unexpected operator
2016-03-01T22:10:15.271Z: /root/coreclr/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00177/lib/init-tools.sh: 43: [: unexpected operator
2016-03-01T22:10:15.271Z: /root/coreclr/packages/Microsoft.DotNet.BuildTools/1.0.25-prerelease-00177/lib/init-tools.sh: 45: [: unexpected operator
2016-03-01T22:10:15.271Z: Unsupported Linux distribution '' detected. Downloading ubuntu-x64 tools.

https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_build?_a=summary&buildId=96654 build has the required logs.

**Comment by ellismg** [comment] 2016-03-01 22:26
We do get lucky in that the CLI that's downloaded is an Ubuntu one which runs here, but this would be good to fix up.

**Comment by gkhanna79** [comment] 2016-03-01 22:28
I thought that was by design since CoreFX repo's init-tools.sh has the same behavior.

**Comment by jasonwilliams200OK** [comment] 2016-03-03 16:05
I think CoreFX is using `1.0.25-prerelease-00182` and the log says in CoreCLR case, it is fetching fetching `00177`. Going by the history of init-tools.sh, https://github.com/dotnet/buildtools/commits/master/src/Microsoft.DotNet.Build.Tasks/PackageFiles/init-tools.sh, it has been changed recently couple of times. Might be worth testing with `prerelease-00182`?

CoreFX: http://dotnet-ci.cloudapp.net/job/dotnet_corefx/job/debian8.2_debug_bld/501/consoleFull

> 22:11:32 Restoring BuildTools version 1.0.25-prerelease-00182...

CoreCLR: http://dotnet-ci.cloudapp.net/job/dotnet_coreclr/job/debug_debian8.2/227/consoleFull

> 16:25:34 Restoring BuildTools...
   ..
   ..
   16:25:48 Installing Microsoft.DotNet.BuildTools.1.0.25-prerelease-00177

**Comment by ellismg** [comment] 2016-03-19 22:46
The problem is that coreclr is invoking the second stage init-tools.sh with `sh` explicitly.  This may or may not be `bash`, which is what the script expects.

The fix is to not invoke the script via sh, instead just call it and let the shebang at the top of the file select bash.

There's a PR to fix this open in CoreCLR and we are discussing it.

**Comment by gkhanna79** [comment] 2016-03-21 16:36
> The problem is that coreclr is invoking the second stage init-tools.sh with sh explicitly.

@ellismg Where is this?

**Comment by ellismg** [comment] 2016-03-21 16:39
See here: https://github.com/dotnet/coreclr/blob/master/init-tools.sh#L110

See also the discussion in dotnet/coreclr#3830, along with my proposed patch.

**Comment by joperezr** [comment] 2016-03-21 17:34
@ellismg this is one of the examples of why it would be a good idea to have this init-tools scripts centralized as you suggest in dotnet/buildtools#558, so that issues like this can be fixed once for all repos in a centralized place.

**Comment by ellismg** [comment] 2016-03-23 03:56
Should be fixed now.

**Closed by ellismg** 2016-03-23 03:56 UTC
Labels: bug
