### ISSUE TITLE
error during RestoreTestRuntimePackage 

### ISSUE THREAD

**Issue by rahku** [dotnet/buildtools#443] opened 2016-02-12 01:39 UTC
I am getting the below error when building any test in coreclr git repo. This is happening because the path does not contain nuget.config file. nuget.config file is at F:\coreclrGit\coreclr\tests\src\nuget.config. But that is neither in path of dotnet.exe nor project.json. RestoreTestRuntimePackage target should specify the source feeds rather than relying on repo nugget.config.

RestoreTestRuntimePackage:
  "F:\coreclrGit\coreclr\tests\..\Tools\dotnetcli/bin/dotnet.exe" restore --packages "F:\coreclrGit\coreclr\tests\..\packages" "F:\coreclrGit\coreclr\Tools\test-runtime/project.json"
F:\coreclrGit\coreclr\Tools\publishtest.targets(17,5): error : Unable to locate Dependency Microsoft.NETCore.TestHost >= 1.0.0-rc2-23712 [F:\coreclrGit\coreclr\tests\src\TestWrappers_x64_Debug\Exceptions\Exceptions.XUnitWrapper.csproj]
F:\coreclrGit\coreclr\Tools\publishtest.targets(17,5): error : Unable to locate Dependency Microsoft.NETCore.Platforms >= 1.0.1-rc2-23712 [F:\coreclrGit\coreclr\tests\src\TestWrappers_x64_Debug\Exceptions\Exceptions.XUnitWrapper.csproj]
F:\coreclrGit\coreclr\Tools\publishtest.targets(17,5): error : Unable to locate Dependency Microsoft.NETCore.Console >= 1.0.0-rc2-23712 [F:\coreclrGit\coreclr\tests\src\TestWrappers_x64_Debug\Exceptions\Exceptions.XUnitWrapper.csproj]
F:\coreclrGit\coreclr\Tools\publishtest.targets(17,5): error : Unable to locate Dependency coveralls.io >= 1.4.0 [F:\coreclrGit\coreclr\tests\src\TestWrappers_x64_Debug\Exceptions\Exceptions.XUnitWrapper.csproj]
  
  Errors in F:\coreclrGit\coreclr\Tools\test-runtime\project.json
      Unable to locate Dependency Microsoft.NETCore.TestHost >= 1.0.0-rc2-23712
      Unable to locate Dependency Microsoft.NETCore.Platforms >= 1.0.1-rc2-23712
      Unable to locate Dependency Microsoft.NETCore.Console >= 1.0.0-rc2-23712
      Unable to locate Dependency coveralls.io >= 1.4.0
F:\coreclrGit\coreclr\Tools\publishtest.targets(17,5): error MSB3073: The command ""F:\coreclrGit\coreclr\tests\..\Tools\dotnetcli/bin/dotnet.exe" restore --packages "F:\coreclrGit\coreclr\tests\..\packages" "F:\coreclrGit\coreclr\Tools\test-runtime/project.json"" exited with code 1. [F:\coreclrGit\coreclr\tests\src\TestWrappers_x64_Debug\Exceptions\Exceptions.XUnitWrapper.csproj]
Done Building Project "F:\coreclrGit\coreclr\tests\src\TestWrappers_x64_Debug\Exceptions\Exceptions.XUnitWrapper.csproj" (default targets) -- FAILED.

**Comment by joperezr** [comment] 2016-02-12 04:12
Yup, there is a trivial fix for this. I'll take care of it.

**Comment by joperezr** [comment] 2016-02-12 20:03
@rahku I was taking a look at the code and it actually doesn't look like a bug on buildtools, the problem seems to be that you are missing [this itemgroup](https://github.com/dotnet/buildtools/blob/master/dir.props#L99) on your dir.props, and then you have to pass it in to the command like we do it [here](https://github.com/dotnet/buildtools/blob/master/dir.props#L125). I'm closing this issue since it's not a bug, but please feel free to ping me if you need help fixing this.

**Closed by joperezr** 2016-02-12 20:03 UTC
