### ISSUE TITLE
CloudTests.targets cleanup 

### ISSUE THREAD

**Issue by MattGal** [dotnet/buildtools#1109] opened 2016-10-08 00:11 UTC
Various small cleanup tasks for @chcosta's review of cherry-picking old commits into the buildtools release/1.0.0 branch.
-  <HelixApiEndpoint Condition="'$(_UseUpdatedHelixApi)'=='true'"> should include and  '$(HelixApiEndpoint)' == ''" 

-HelixJobType Property:
This all looks very tightly coupled, but weakly regulated. ie, it would be easy for someone to miss updating one of these values. A structure like this would be slightly more flexible / manageable...

``` xml
  <PropertyGroup>
    <HelixJobTypeBase Condition="'$(HelixJobTypeBase)' == ''">test/functional/</HelixJobTypeBase>
  </PropertyGroup>
  <PropertyGroup>
    <HelixJobTypeModifier Condition="'$(FilterToTestTFM)'=='netcore50' and !$(TestNugetRuntimeId.Contains('aot'))">uwp/</HelixJobType>  
    <HelixJobTypeModifier Condition="'$(FilterToTestTFM)'=='netcore50' and $(TestNugetRuntimeId.Contains('aot'))">ilc</HelixJobTypeModifier >  
    <HelixJobTypeModifier Condition="$(FilterToTestTFM.Contains('net46'))">desktop/cli</HelixJobTypeModifier >  
    <HelixJobTypeModifier Condition="'$(HelixJobTypeModifier )'=='' And '$(Performance)'=='true'">perf/cli</HelixJobTypeModifier >  
    <HelixJobTypeModifier Condition="'$(HelixJobTypeModifier )'==''">cli</HelixJobTypeModifier >      
  </PropertyGroup>
  <PropertyGroup>
    <HelixJobType Condition="'$(HelixJobType)' == ''">$(HelixJobTypeBase)$(HelixJobTypeModifier)/</HelixJobType>
  </PropertyGroup>
```
- Consider making Helix API end point(s) unique properties defined near the top of the file (for ease of discovery), and then just replace the hard-coded definitions here with the respective properties.

RelativeBlobPathFolderContainingTests : 
This appears to be an internal only property, you could add the '_' suffix. Additionally, changing this to...

``` xml
<RelativeBlobPathFolderContainingTests>Tests</RelativeBlobPathFolderContainingTests>  
<RelativeBlobPathFolderContainingTests Condition="'$(FilterToTestTFM)' != ''" >$(RelativeBlobPathFolderContainingTests)/$(FilterToTestTFM)</RelativeBlobPathFolderContainingTests>  
```

... means that if you have to change the path, you only have to update one of these properties and not remember to update both.

**Comment by dleeapho** [comment] 2017-03-03 22:39
Dupe of dotnet/core-eng/#1368

**Closed by dleeapho** 2017-03-03 22:39 UTC
