### ISSUE TITLE
GenApi generates incorrect C# for value tuples

### ISSUE THREAD

**Issue by natemcmaster** [dotnet/buildtools#2071] opened 2018-06-16 00:56 UTC
Example api:
https://github.com/aspnet/Mvc/blob/1aea6fd5bd4d41ba68efca3708d26ee02b72a2d1/src/Microsoft.AspNetCore.Mvc.Core/Internal/ActionAttributeRouteModel.cs#L12

Example generated source:
```c#
namespace Microsoft.AspNetCore.Mvc.Internal
{
    public static partial class ActionAttributeRouteModel
    {
        public static [System.Runtime.CompilerServices.TupleElementNamesAttribute(new string[]{ "route", "actionSelector", "controllerSelector"})]System.Collections.Generic.IEnumerable<System.ValueTuple<Microsoft.AspNetCore.Mvc.ApplicationModels.AttributeRouteModel, Microsoft.AspNetCore.Mvc.ApplicationModels.SelectorModel, Microsoft.AspNetCore.Mvc.ApplicationModels.SelectorModel>> GetAttributeRoutes(Microsoft.AspNetCore.Mvc.ApplicationModels.ActionModel actionModel) { throw null; }
    }
}
```

This does not compile
```
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,27): error CS1031: Type expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,28): error CS0270: Array size cannot be specified in a variable declaration (try initializing with a 'new' expression) [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,166): error CS1003: Syntax error, ',' expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,167): error CS1003: Syntax error, '>' expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,167): error CS1003: Syntax error, '(' expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,204): error CS1001: Identifier expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,210): error CS1001: Identifier expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,216): error CS1001: Identifier expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,216): error CS1003: Syntax error, ',' expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,218): error CS1003: Syntax error, ',' expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,234): error CS1001: Identifier expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,234): error CS1003: Syntax error, ',' expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,441): error CS1026: ) expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
C:\dev\aspnet\asplabs\pkg\src\Microsoft.AspNetCore.App.RefOnly\src\Microsoft.AspNetCore.Mvc.Core.cs(1736,441): error CS1001: Identifier expected [C:\dev\aspnet\asplabs\pkg\src\refcompiler\refcompiler.csproj]
```

I'm using Microsoft.DotNet.BuildTools.GenApi/2.2.0-preview1-02914-01

**Comment by weshaggard** [comment] 2018-07-06 22:12
This is a duplicate of https://github.com/dotnet/buildtools/issues/1850.

**Closed by weshaggard** 2018-07-06 22:12 UTC
Labels: area-buildtools-code
