### ISSUE TITLE
CopyTestToTestDirectory ignores subdirectories

### ISSUE THREAD

**Issue by ericstj** [dotnet/buildtools#343] opened 2015-11-30 22:52 UTC
Items that have a relative path are all copied to the same directory due to CopyTestToTestDirectory ignoring targetpath information of items.

It also removes items that have the same name but different directories.

**Comment by MattGal** [comment] 2016-10-04 20:39
@ericstj I don't know exactly when but this has been working for some time;  for instance, various tests depend on copying their content to recursively defined sub directories, like the System.Private.Xml tests.

**Comment by naamunds** [comment] 2016-11-15 23:21
It looks like the current behavior is that the following items are copied to recursive subdirectories of the test directory:
- Items in `@(ContentWithTargetPath)`
- Items in `@(SupplementalTestData)`
- Items in `@(_TestCopyLocalAppXRunner)`

Other items, including `@(AllItemsFullPathWithTargetPath)`, are copied directly to the test directory, even if they have `TargetPath` metadata.

@ericstj Is this the expected behavior?  If the current behavior isn't correct, can you give an example of a test project where this isn't working?

@MattGal It looks like some System.Private.Xml tests have files in recursive subdirectories, but just from `@(SupplementalTestData)` that I've seen, so I'm not sure if that's what @ericstj was referring to.

**Comment by MattGal** [comment] 2016-11-15 23:31
@naamunds I believe the flattening behavior mentioned was intended at some point, and SupplementalTestData was used as a means to work around this.    However that stuff is copied in CopySupplementalTestData and Eric is talking about CopyTestToTestDirectory 

If you look at the copying here:
https://github.com/dotnet/buildtools/blob/9236c061be9cd7c73eeb822f50a29b46f2eca27f/src/Microsoft.DotNet.Build.Tasks/PackageFiles/publishtest.targets#L110

... we see that only ContentWithTargetPath gets a destination that isn't intentionally "flattened", and as far as I can tell nothing ever actually populates that item group any more (i.e. it's been unintentionally? obsoleted).

Tweaking at the line above should allow you to include sub directories if needed, but for things like Content SupplementalTestData serves well.  If there were, for instance, a build output like en-us\foo.resources.en-us.dll that needed to exist for the test, we'd need to tweak this.

**Comment by naamunds** [comment] 2016-11-15 23:35
Makes sense.  Should we go ahead and close this issue then?

**Comment by ericstj** [comment] 2016-11-16 00:22
I can't remember what I was doing when I opened this last year, but I suspect I was helping someone onboard a test that needed subdirectories and we worked around it.  I'm ok closing giving its so stale.

**Closed** 2016-11-16 00:28 UTC
Labels: 3 - Done, bug
